### ISSUE TITLE
Dag Dependency page not showing anything

### ISSUE THREAD

**Issue by SamiRehmanNostra** [apache/airflow#16610]
**Apache Airflow version**: 2.1.

**Environment**: Ubuntu 20.04

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): UBUNTU 20.04 LTS
- **Kernel** (e.g. `uname -a`): Linux 20.04.1-Ubuntu SMP Tue Jun 1 09:54:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: python and pip

**What happened**: After performing the upgrade from 2.0.2 to 2.10 using the guide available in the documentation, Airflow upgraded successfully, Dag dependency page isn't  working as expected.
The DAG dependency page doesn't show the dependency graph.

**What you expected to happen**: I expected the dag dependency page to show the dags and their dependency in a Graph view

**How to reproduce it**: Its reproduced by opening these pages every time. 

![Dag Dependency Page](https://user-images.githubusercontent.com/43160555/123028222-6eee0000-d422-11eb-9664-a8c0ee2a6723.png)

How often does this problem occur? Once? Every time etc?
Every time

Any relevant logs to include? Put them here in side a detail tag:
<details><summary>Upgrade Check  Log</summary> 

/home/ubuntu/env_airflow/lib/python3.8/site-packages/airflow/configuration.py:34                                            
6 DeprecationWarning: The hide_sensitive_variable_fields option in [admin] has been moved to the hide_sensitive_var_conn_fields option in [core] - the old setting has been used, but please update your config.
/home/ubuntu/env_airflow/lib/python3.8/site-packages/airflow/configuration.py:34                                            
6 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
/home/ubuntu/env_airflow/lib/python3.8/site-packages/airflow/plugins_manager.py:                                            
239 DeprecationWarning: This decorator is deprecated.In previous versions, all subclasses of BaseOperator must use apply_default decorator for the`default_args` feature to work properly.
In current version, it is optional. The decorator is applied automatically using the metaclass.
/home/ubuntu/env_airflow/lib/python3.8/site-packages/airflow/configuration.py:34                                           
6 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.

 </details>

**Comment by bbovenzi** [comment]
@SamiRehmanNostra Could you open the browser console and screenshot any error messages in the logs?

**Comment by SamiRehmanNostra** [comment]
Hi @bbovenzi ,

Please see the screenshot attached below:
![Browser Screenshot](https://user-images.githubusercontent.com/43160555/123727628-46a84a80-d8d5-11eb-9b0e-cc5c17c51dec.png)


`d3.min.js:1 Error: <g> attribute transform: Expected number, "translate(NaN,20)scale(0)".
i @ d3.min.js:1
Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
d3.min.js:1 Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
i @ d3.min.js:1
d3.min.js:1 Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
i @ d3.min.js:1
d3.min.js:1 Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
i @ d3.min.js:1
d3.min.js:1 Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
i @ d3.min.js:1
d3.min.js:1 Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
i @ d3.min.js:1
d3.min.js:1 Error: <g> attribute transform: Expected number, "translate(NaN,NaN)scale(0)".
i @ d3.min.js:1
`
Let me know if you need any more information.

Thank you,
Sami

**Comment by ashb** [comment]
@SamiRehmanNostra Do you by chance have no dags at all?

**Comment by SamiRehmanNostra** [comment]
@ashb I have about 13 active dags, all running on different schedules.
Weirdly enough I was installing a bunch of ODBC drivers today and restarted the web-server about 3 times. The issue seems to have resolved itself.

![image](https://user-images.githubusercontent.com/43160555/123765008-ac61fa00-d908-11eb-80af-297a9f8269e9.png)

 Not sure what has changed. Let me know if I need to share any logs.

**Comment by ashb** [comment]
Hmmm tricky. Without having a reliable way of reproducing this it's going to be tricky to fix.

Did you clear the DB when restarting the webserver? (Not likely, just checking)

**Comment by bbovenzi** [comment]
@ashb I have been able to reliably replicate it. If I only run the webserver the returned [nodes and edges](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L4130-L4131`) will be empty arrays. As soon as I run the scheduler both will populate and the graph will render.

**Comment by ashb** [comment]
@bbovenzi Cool -- lets protect against that case as it is _a_ cause of this problem.

**Comment by bbovenzi** [comment]
Yeah, I'll add some sort of "Dependency data could not be loaded right now" error message.

**Comment by SamiRehmanNostra** [comment]
@ashb I didn't reset the DB. Seems like @bbovenzi has narrowed it down. Thank you

**Comment by SamiRehmanNostra** [comment]
@bbovenzi Its back people!

![image](https://user-images.githubusercontent.com/43160555/124052826-82244f80-da62-11eb-9a87-92a9749b9337.png)

**Comment by ManiBharataraju** [comment]
@bbovenzi @ashb - It appears like for a fresh build this piece of code is setting value as None.
https://github.com/apache/airflow/blob/9a1fc19a627662122dd8dacee2ef61c3edf97b85/airflow/serialization/serialized_objects.py#L682

We just upgraded to 2.1.1 and see the dag dependencies empty. Tried restarting the scheduler multiple times but doesn't help.

Could it be possible that task_type in the below piece of code returns BaseOperator instead of the actual operator? IDK, haven't been able to reproduce this issue in my local.
https://github.com/apache/airflow/blob/9a1fc19a627662122dd8dacee2ef61c3edf97b85/airflow/serialization/serialized_objects.py#L341

I see this error message on the UI
<img> 
![image](https://user-images.githubusercontent.com/9946408/125763690-c101ebd6-147f-405e-8735-e1c4051537b9.png)

**Comment by xiaoxugao** [comment]
Hey, is this issue solved? I still have the same problem as @SamiRehmanNostra .

**Comment by SamiRehmanNostra** [comment]
Hi @xiaoxugao ,

I might need to open another issue, I upgraded to 2.2.0 I initially had no issues, but over the last couple of weeks been having some issues again.

![image](https://user-images.githubusercontent.com/43160555/147996739-498d2513-b431-4131-8244-d32b0a2e8263.png)

Not sure what the error is apart from this JS error.

Thank you,
Sami

**Comment by bbovenzi** [comment]
@xiaoxugao what version of airflow are you using?

**Comment by bbovenzi** [comment]
We can just reopen this issue. You're right that it should've been fixed in 2.2.0. Let me replicate and see if something different is going on.

**Comment by TerryYin1777** [comment]
any updates on this? I have the same issue with @SamiRehmanNostra. I'm on airflow 2.2.2

**Comment by bbovenzi** [comment]
> any updates on this? I have the same issue with @SamiRehmanNostra. I'm on airflow 2.2.2

Yes, I finally got back around to debugging this and I think I found a fix.

**Comment by rvatsastro** [comment]
working as expected now
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/102275369/178228612-f4d75aae-6695-4c60-8e16-3442c5bdbed6.png">

**Comment by sthakkar-move** [comment]
@rvatsastro thanks for reporting. did you have to do anything to resolve the issue ? We are on MWAA 2.0.2 and still seeing the same issue
<img width="878" alt="image" src="https://user-images.githubusercontent.com/128174672/232832171-0fbfce94-a81a-4983-958b-7ff89b4d2e9c.png">

**Comment by leozitor** [comment]
Hey guys is anyone facing issues regarding this, I notices in my code that if i have a TriggerDagRunOperator inside task_group like this, it shows the dag dependency on viewer
```
@task_group(group_id='concat_video')
    def concatenate_video(task_id: int):
        print("triggering job")
        submit_job = TriggerDagRunOperator(
            task_id='submit_job',
            trigger_dag_id='video_concatenation_job',
            wait_for_completion=True,
            deferrable=True,

            poke_interval=10,
            conf={
                    'task_id': task_id,
                },
            )

        submit_job
```
![Screenshot from 2023-10-24 10-11-57](https://github.com/apache/airflow/assets/2281027/c9dce9cd-53f7-4a22-a450-3dc64e43c13f)

but if I use without a task_group ( for this example doesn't make sense to use a group for a unique task)
it doesn't show in dag dependency viewer 
```   
@task
def concatenate_video(task_id: int):
         print("triggering job")
         submit_job = TriggerDagRunOperator(
          task_id='submit_job',
          trigger_dag_id='video_concatenation_job',
          wait_for_completion=True,
          deferrable=True,
          # max_active_tis_per_dag=2, # it may be used if not deferrable
          poke_interval=10,
          conf={
                  'task_id': task_id,
              },
          )

      submit_job
```
Does this make a sense?
