### ISSUE TITLE
Constant "The scheduler does not appear to be running" warning on the UI following 2.6.0 upgrade

### ISSUE THREAD

**Issue by arjunanan6** [apache/airflow#31200]
### Apache Airflow version

2.6.0

### What happened

Ever since we upgraded to Airflow 2.6.0 from 2.5.2, we have seen that there is a warning stating "The scheduler does not appear to be running" intermittently.

This warning goes away by simply refreshing the page. And this conforms with our findings that the scheduler has not been down at all, at any point. By calling the /health point constantly, we can get it to show an "unhealthy" status:

These are just approx. 6 seconds apart: 

```
{"metadatabase": {"status": "healthy"}, "scheduler": {"latest_scheduler_heartbeat": "2023-05-11T07:42:36.857007+00:00", "status": "healthy"}}

{"metadatabase": {"status": "healthy"}, "scheduler": {"latest_scheduler_heartbeat": "2023-05-11T07:42:42.409344+00:00", "status": "unhealthy"}}
```

This causes no operational issues, but it is misleading for end-users. What could be causing this? 

### What you think should happen instead

The warning should not be shown unless the last heartbeat was at least 30 sec earlier (default config).  

### How to reproduce

There are no concrete steps to reproduce it, but the warning appears in the UI after a few seconds of browsing around, or simply refresh the /health endpoint constantly.

### Operating System

Debian GNU/Linux 11

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.0.0
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-cncf-kubernetes==6.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-docker==3.6.0
apache-airflow-providers-elasticsearch==4.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-google==10.0.0
apache-airflow-providers-grpc==3.1.0
apache-airflow-providers-hashicorp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-azure==6.0.0
apache-airflow-providers-microsoft-mssql==3.3.2
apache-airflow-providers-microsoft-psrp==2.2.0
apache-airflow-providers-microsoft-winrm==3.0.0
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-oracle==3.0.0
apache-airflow-providers-postgres==5.4.0
apache-airflow-providers-redis==3.1.0
apache-airflow-providers-sendgrid==3.1.0
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-slack==7.2.0
apache-airflow-providers-snowflake==4.0.5
apache-airflow-providers-sqlite==3.3.2
apache-airflow-providers-ssh==3.6.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Deployed on AKS with helm

### Anything else

None more than in the description above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
@arjunanan6  and @PhoenixChamb  could you please increase the https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#job-heartbeat-sec to say 7 s  and then increase it to 10 if it does not help (if you have default 5) and see if that decreases the probability of such an event and report it back here?

That would help us to be able to see if just increasing the default is a good idea because of increased resources in 2.6 or whether we have some other problem.

**Comment by arjunanan6** [comment]
@potiuk  On it, I will report back shortly.

**Comment by ptran32** [comment]
We also faced this issue after upgrading from Airflow 2.5.3 to 2.6.0

https://gist.github.com/ptran32/56703c86a854ec80bdae1d5195c182e7

**Comment by ptran32** [comment]
> As @ptran32 noted, we are also seeing unnecessary restarts for the scheduler because a livenessprobe failed. Interestingly, this was not a problem today, but something that started late last night - several hours after the upgrade.
> 
> But, I really cannot see any issues from the scheduler logs that would cause the probe to fail. As a temporary solution, I am trying out increasing the following values:
> 
> * scheduler.livenessProbe.timeoutSeconds to 30
> * scheduler.livenessProbe.failureThreshold to 10
> 
> Hopefully, this results in no/fewer restarts.

Hi,

 if you are using Helm to deploy Airflow, the 3.6.0 version will cause the scheduler to restart in loop, not because of the timeout but because the liveness check is not compatible with the new release


Scheduler logs after upgrade to 3.6.0

```
Liveness probe failed: Traceback (most recent call last): File "<string>", line 2, in <module> ModuleNotFoundError: No module named 'airflow.jobs.scheduler_job'
``` 

We fixed it by adjusting the liveness check command in the helm chart:

```
      livenessProbe:
          exec:
            command:
            - python
            - -Wignore
            - -c
            - |
              from typing import List
              from airflow.jobs.scheduler_job_runner import SchedulerJobRunner
```

I hope it helps.

**Comment by rcheatham-q** [comment]
I can confirm that the default liveness probe for the scheduler is failing. The helm chart v1.9.0 defines the liveness probe as follows:

```
CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint airflow jobs check --job-type SchedulerJob --local
```

However, executing that command on a live and functioning scheduler pod fails (I omitted the `exec` command so I could check the exit code):

```
airflow@airflow-scheduler-866db5c895-qt5pq:/opt/airflow$ CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR /entrypoint airflow jobs check --job-type SchedulerJob --local
No alive jobs found.
airflow@airflow-scheduler-866db5c895-qt5pq:/opt/airflow$ echo $?
1
airflow@airflow-scheduler-866db5c895-qt5pq:/opt/airflow$ 
```

I can confirm that the liveness check listed by @ptran32 does function, however it does not seem to directly detect if the scheduler job is running.

I also tested the example `airflow jobs check` commands listed in [the CLI docs](https://airflow.apache.org/docs/apache-airflow/2.6.0/cli-and-env-variables-ref.html#check_repeat1) and both functioned the same.

It appears that the scheduler healthchecks in general are broken in version 2.6.0.

**Comment by ptran32** [comment]
@rcheatham-q that might help as a workaround for now: https://github.com/airflow-helm/charts/pull/738

**Comment by potiuk** [comment]
> @rcheatham-q that might help as a workaround for now: [airflow-helm/charts#738](https://github.com/airflow-helm/charts/pull/738)

This is not the problem. The workaround is in the non-Airflow community managed Helm chart that did not catch up with the new scheduler probe and even the workaround there is very wrong. This is a different issue (And I am looking into it now). I doubt it is caused by liveness check not working (it works in general). This is a different issue.

**Comment by potiuk** [comment]
I would love to get to the bottom of it. Can anyone having the problem (with the Airflow Community chart) run the following on their frequently failing scheduler:

1) exec into the container of scheduler while it is running (`/entrypoint bash` should be the right command

2) Run this command:

* `date`
*  then `AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG airflow jobs check --job-type SchedulerJob --local`  several times while airflow is running and save somewhere the output
* if you notice that it switches from finding 1 job alive into `No alive jobs found.` do as follows
*`date`
* run `airflow db shell`
* run 'SELECT * from job;' 
* copy the output
* repeat few times and see if it changes (last time seen)
* When your scheduler gets killed because of liveness checks -> find the logs of scheduler from before that faiure and dump them
* create some way (gists?) to share all the dumped information (please annotate and comment where the log is from)

And ping me.

@ptran32 @rcheatham-q @arjunanan6 - can I count on your help here?

**Comment by potiuk** [comment]
@PhoenixChamb - you as well ^^ Can I count on your help too ?

**Comment by thesuperzapper** [comment]
@potiuk on a related note, I believe that the [`scheduler_health_check_threshold`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#scheduler-health-check-threshold) config is ignored since airflow 2.6.0, this is because [`SchedulerJobRunner.is_alive()`](https://github.com/apache/airflow/blob/3193857376bc2c8cd2eb133017be1e8cbcaa8405/airflow/jobs/scheduler_job_runner.py#L267-L286) is not called anymore, only the [`Job.is_alive()`](https://github.com/apache/airflow/blob/3193857376bc2c8cd2eb133017be1e8cbcaa8405/airflow/jobs/job.py#L123-L137) which does not consider the config. This is because, since PR https://github.com/apache/airflow/pull/30302, the SQL query used by the `/health` endpoint returns a `Job` rather than a `SchedulerJobRunner` instance. 

This means that the [`job_heartbeat_sec`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#job-heartbeat-sec) is used instead, and as that has a default of `5` seconds (compared with the `scheduler_health_check_threshold` default of `30`), I expect we will see many users reporting their Schedulers are unhealthy.

Also, I think airflow's internal checking for the health of the scheduler is NOT affected by this bug, as it looks like [`adopt_or_reset_orphaned_tasks()`](https://github.com/apache/airflow/blob/3193857376bc2c8cd2eb133017be1e8cbcaa8405/airflow/jobs/scheduler_job_runner.py#L1565) correctly uses `scheduler_health_check_threshold`.

**Comment by thesuperzapper** [comment]
After thinking about it, I think the easiest way to fix the issue I described in https://github.com/apache/airflow/issues/31200#issuecomment-1546765025 is to update [`Job.is_alive()`](https://github.com/apache/airflow/blob/3193857376bc2c8cd2eb133017be1e8cbcaa8405/airflow/jobs/job.py#L123-L137) to specifically check if its `self.job_type` is `"SchedulerJob"`, and in that case, use the same logic as [`SchedulerJobRunner.is_alive()`](https://github.com/apache/airflow/blob/3193857376bc2c8cd2eb133017be1e8cbcaa8405/airflow/jobs/scheduler_job_runner.py#L267-L286).

**Comment by thesuperzapper** [comment]
For anyone watching who wants a workaround for Airflow 2.6.0, you can simply set [`AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#job-heartbeat-sec) to `30`, or whatever you had [`AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#scheduler-health-check-threshold) set to.

**Comment by rcheatham-q** [comment]
> For anyone watching who wants a workaround for Airflow 2.6.0, you can simply set [`AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#job-heartbeat-sec) to `30`, or whatever you had [`AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD`](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#scheduler-health-check-threshold) set to.

I can confirm that this workaround removes the warning from the UI and the updated liveness probe in the linked PR also works. Thanks @thesuperzapper for the workarounds.

@potiuk given what @thesuperzapper has described, do you still need the debugging data you mentioned? I'm happy to provide it, but don't want to go through the effort if it is no longer required.

**Comment by potiuk** [comment]
Thanks @thesuperzapper ! 

This is a fantastic find! Thanks for the analsis - really helpful and absolutely @rcheatham-q and others - no need for the analysis. 

Indeed, there was a separate case for scheduler job where instead of the 2.1 grace period we overwrote it with the configuration value - and both the configuration value and `is_alive` in SchedulerJobRunner have not been used.

I am applying a fix now that will make it into rc3 of 2.6.1 - and it will fix both the `/health` endpoint and `airflow jobs check` command to use the configuration variable for the check.

Still I think (just a comment the @thesuperzapper) you should change your Helm Chart to use `airflow jobs check` as of 2.6.1. As of 2.6 we are far more precise on what is and what is not the public interface of Airlfow - and things will break without a warning (even in patchlevel releases) if you base your API interfacing with alrflow on database structure, specific queries, and "random" airflow code executed from outside. While there might be occasional bugs like this one where we missed a case during refactoring, those will be quickly fixed (this one in 2.6.1) and they will remain forward-compatible (`airlfow jobs check` aim is to provide the right check - for example if we get rid of Job table in the future - which might happen without a warning in any release - it will continu to work).

**Comment by potiuk** [comment]
Fix in #31277

**Comment by arjunanan6** [comment]
@potiuk I pushed the suggested change from @thesuperzapper about an hour ago and everything looks fine now. No more warnings on the UI, or scheduler restarts. Thanks a lot!

**Comment by potiuk** [comment]
Yes. Thanks @arjunanan6 -> we just also merged #31277 with the fix to 2.6.1 (and rc3 will be up shortly for voting/testing - so if you want to take it to a spin for 2.6.1 and revert back to the original settings/configuration, that would be perfect.

**Comment by thesuperzapper** [comment]
> Still I think (just a comment the @thesuperzapper) you should change your Helm Chart to use `airflow jobs check` as of 2.6.1 - see my comment here: https://github.com/airflow-helm/charts/pull/738#issuecomment-1546851124 . 
> 
> As of 2.6 we are far more precise on what is and what is not the [public interface of Airlfow](https://airflow.apache.org/docs/apache-airflow/stable/public-airflow-interface.html) - and things will break without a warning (even in patchlevel releases) if you base your API interfacing with Alrflow: specifically when relying on database structure, specific queries, and "random" airflow code executed from outside. You've been warned.
> 
> While there might be occasional bugs like this one where we missed a case during refactoring, those will be quickly fixed (this one in 2.6.1) and they will remain forward-compatible (`airlfow jobs check` aim is to provide the right check - for example if we get rid of Job table in the future - which might happen without a warning in any release - it will continue to work).  
> 

@potiuk the problem is that I'm doing a slightly more complex check than just if there is a `SchedulerJob` running.

There is an optional secondary check that ensures tasks are actually being scheduled (in the form of new `LocalTaskJob` appearing), but this check is only started once at least one scheduler has been running for a minimum period (to prevent deadlocks where the probe restarts the scheduler before it gets a chance to schedule something).

The reason we need this check is because older versions of airflow will sometimes deadlock and not schedule new tasks but still have a heartbeat, so they look healthy to the normal probe.

I'm not sure that this is possible to achieve with the current `airflow jobs check`.

**Comment by potiuk** [comment]
> I'm not sure that this is possible to achieve with the current airflow jobs check.

For sure you can do it with an API. 

Or maybe this is a great idea to contribute such check to Airflow. This is the only way to make sure that anything you do there is not going to change in the next version. If you do not have unit tests covering it and making sure that regression tests are passing, there is no way we can maintain backwards compatibility of the code. If yuou have not made any effort (by adding and making sure that the tests are in Airflow that can guarantee something, we are not able to promise absolutely anything.

This is one of the reasons why the bug crept into 2.6.0 - because it had no test to prevent regressions - now it has https://github.com/apache/airflow/pull/31277/files#diff-9499319fda165fa31190eba1879d7ecf71871ce3536da0a8505ba529378095c7R151

 It would be absolutely unreasonable to expect that things will not change - code is a living thing. And what Airflow team can do is to  promise that will make all the effort to keep the things that are public interface backwards compatible.

And this is what [public interface of Airflow](https://airflow.apache.org/docs/apache-airflow/stable/public-airflow-interface.html)  document is about. Look there. If you find something that is not there, don't rely on it. Even more if you find that something is specifically excluded (like direct DB access) - don't use it even more. Figure a different way (Stable REST API is a good idea). Just stick to it. There is no argument about it anyway, until you bring the diccussion into the devlist and convince the people to change their decision about it.  You have to change your ways or things will break. You have been warned (for the third time).

And just to make a bit more illustration of what you are asking for. I know it's largely exaggerated and what you want is no not as extreme as this but the line of thinking you have here is very similar to this one:

![image](https://github.com/apache/airflow/assets/595491/fb3b26e5-24e3-48db-98b9-bc87952edbc3)

But with Airlfow explicitly defining what is public interface and what is not, you are basicaly asking for this^^

**Comment by Atif8Ted** [comment]
we are still facing the issue . the health endpoint still shows `scheduler` as unhealthy randomly. We are using 2.6.2
