### ISSUE TITLE
Triggering a DAG Run from the DAG Graph View does not redirect to the triggered DAG Run page

### ISSUE THREAD

**Issue by pedro-cf** [apache/airflow#37935]
### Apache Airflow version

**2.9.1**

### What happened?

Triggering a DAG Run from the DAG Graph View does not redirect to the triggered DAG Run page.

![2024-03-06 11-28-12](https://github.com/apache/airflow/assets/4175430/bf1060a1-7418-415a-906c-33bcad1f5f1c)

### What you think should happen instead?

After Triggering a DAG Run from the DAG Graph View  the user should be redirected to the graph view of the DAG RUN he just triggered.

### How to reproduce

1. Ensure **'AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW'** is set to **'graph'**
2. Click on a DAG that has Parameters.
3. Go to the graph View
4. Click the Trigger DAG Run button.
5. Trigger DAG Run
6. You will not be redirected to the graph view of this latest DAG Run you just triggered.

(see gif above)

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Docker-Compose

### Deployment details

Docker Compose version v2.2.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
I do not fully understand what you mean with "the triggered DAG Run page" - do you assume the resulting page after triggering should jump to the details of the "new run just triggered" or what detail do you expect? Also the video recording does not explicitly tell me.
Is this only happening if you configure the graph view as default as you explicitly state this in the details?

Note that when you open the "trigger DAG" view the URL in the browser should contain the "origin-URL" which is used to direct the user back to. Can you please post the origin URL in this case and the URL you expect to be directing to?

**Comment by pedro-cf** [comment]
> do you assume the resulting page after triggering should jump to the details of the "new run just triggered"

Yes, this was working like this up to version 2.8.1

> Also the video recording does not explicitly tell me

As you can see in the GIF:

**1st state**: before triggering the DAG Run the current and latest DAG run that is viewed is `2024-03-06, 11:25:14 UTC`
![image](https://github.com/apache/airflow/assets/4175430/535c0dfa-2ab1-42db-99b7-bbb547619905)

**2nd state**:  after triggering the DAG Run, the same previous DAG run is still viewed `2024-03-06, 11:25:14 UTC`
![image](https://github.com/apache/airflow/assets/4175430/fd6a560d-bba1-4344-acff-ee63cf5779c9)

**3rd state**: after click the "GRAPH" button to refresh the page the GA run displayed is `2024-03-06, 11:18:16 UTC`
![image](https://github.com/apache/airflow/assets/4175430/6804f982-fe82-4ef8-a96b-103fdec0a29f)


> Is this only happening if you configure the graph view as default as you explicitly state this in the details?

I am unsure of this, but I thought it could be related since my airflow is setup like so.

**Comment by jscheffl** [comment]
Okay, now I understand and made a small test myself.

The problem described appears actually in tabs "Graph" and "Gantt". Root cause is that the trigger-button renders the parameter `&dag_run_id=manual__2024-03-07T21%3A11%3A16%2B01%3A00` into the origin URL, if the trigger page returns to this origin and uses the `dag_id` in the return call, the page will not have auto-refresh on and therefore will not display the new DAG run.

**Comment by jscheffl** [comment]
I tested this to fix it finally in Airflow 2.9.0 as upcoming release. I needed to realize that due to changes in UI structure and rework of the layout the problem has been resolved on it's own. As there will be very probably no fix be supplied in Airflow 2.8.x I am going to close this buf. It is implicitly frixed with 2.9.0

**Comment by pedro-cf** [comment]
This is still an issue in 2.9.0 @jscheffl

**Comment by jscheffl** [comment]
I would very much assume from the original problem, in 2.9.0 there was a different issue. Not "debating" about details, I'd assume it is fixed with #38941

**Comment by pedro-cf** [comment]
Can this issue be re-opened ?

**Comment by jscheffl** [comment]
@pedro-cf of course the ticket _could_ be re-opened - but I did a regression with current main and I can confirm that #38941 fixed this problem - which is planned to be released with 2.9.1.

What would be the benefit to open the ticket for a bug that is fixed already? Current approach with the tickets is to close tickets as soon as a fix is merged.
If you feel with current main you can still run into a problem - can you please describe which detail is missing? Do I over-look a detail?

**Comment by pedro-cf** [comment]
Greetings @jscheffl it seems this bug still exists in `2.9.1`

**Comment by jscheffl** [comment]
@pedro-cf Maybe I do not full yunderstand you or we are not on the same page. I did a regression via `docker run -it --rm -p 8080:8080 -e AIRFLOW__CORE__LOAD_EXAMPLES=True -e AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph apache/airflow:2.9.1-python3.8 airflow standalone` and was then opening my browser on http://localhost:8080/ - all is looking fine. I tested with one example DAG included. After trigger the new run is immediately displayed.

Can you describe the steps you did and where you miss something? Maybe a screen recording?

**Comment by pedro-cf** [comment]
> @pedro-cf Maybe I do not full yunderstand you or we are not on the same page. I did a regression via `docker run -it --rm -p 8080:8080 -e AIRFLOW__CORE__LOAD_EXAMPLES=True -e AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph apache/airflow:2.9.1-python3.8 airflow standalone` and was then opening my browser on http://localhost:8080/ - all is looking fine. I tested with one example DAG included. After trigger the new run is immediately displayed.
> 
> Can you describe the steps you did and where you miss something? Maybe a screen recording?

I have gif at the top of the page showing exactly what happens.

**How to recreate:**
1. Click on a DAG
2. Go to graph View
3. Click the Trigger DAG Run button.
4. Trigger DAG Run
5. You will not be redirected to the graph view  of this latest DAG Run you just triggered.

**Expected behaviour:**
- Redirected to the graph view of the DAG RUN you just triggered.

**Comment by pedro-cf** [comment]
Updated the issue description. Would be cool if someone could update the label since it affects version 2.9.1 @eladkal

**Comment by jscheffl** [comment]
Okay, then I assume I now understand the mis-understanding. Please correct me if I am right:

In 2.8.2 the main problem was the new DAG run was "hidden". This is what in 2.9.1 now is fixed. The new DAG run appears after triggering.

BUT you expect the new DAG run being selected. But after triggering the Grid view shows the DAG with all runs, no explicit run selected.

So in technical detail for step (5) currently the user is directed to `http://localhost:28080/dags/example_params_trigger_ui/grid` but you want the user to be directed to `http://localhost:28080/dags/example_params_trigger_ui/grid?dag_run_id=manual__2024-05-11T21%3A22%3A49%2B02%3A00` (assuming the run_id in this example is the one which was just triggered).

If this is correctly understood... then it is not a bug but a new feature. Still a small one. Will change the tags.

**Comment by pedro-cf** [comment]
> In 2.8.2 the main problem was the new DAG run was "hidden". This is what in 2.9.1 now is fixed. The new DAG run appears after triggering.

That's interesting you mention it. It's a bit random.

After some additional testing sometimes thew new DAG run is hidden. and sometimes it's visible but not selected.

**Comment by pedro-cf** [comment]
> Okay, then I assume I now understand the mis-understanding. Please correct me if I am right:
> 
> In 2.8.2 the main problem was the new DAG run was "hidden". This is what in 2.9.1 now is fixed. The new DAG run appears after triggering.
> 
> BUT you expect the new DAG run being selected. But after triggering the Grid view shows the DAG with all runs, no explicit run selected.
> 
> So in technical detail for step (5) currently the user is directed to `http://localhost:28080/dags/example_params_trigger_ui/grid` but you want the user to be directed to `http://localhost:28080/dags/example_params_trigger_ui/grid?dag_run_id=manual__2024-05-11T21%3A22%3A49%2B02%3A00` (assuming the run_id in this example is the one which was just triggered).
> 
> If this is correctly understood... then it is not a bug but a new feature. Still a small one. Will change the tags.

Greetings @jscheffl , not sure if this was included in the `2.9.2` release, but in `2.9.2`:
-  new DAG Runs are still hidden (sometimes) 
-  the new DAG run is not selected.

**Comment by potiuk** [comment]
> Greetings @jscheffl , not sure if this was included in the 2.9.2 release, but in 2.9.2:

If you look at the PR, it's marked as 2.10.0 milestone.

**Comment by pedro-cf** [comment]
> > Greetings @jscheffl , not sure if this was included in the 2.9.2 release, but in 2.9.2:
> 
> If you look at the PR, it's marked as 2.10.0 milestone.

sorry about that, I will delete.

**Comment by pedro-cf** [comment]
Greetings @potiuk @jscheffl , any chance this issue can be reopened, or should I make a new one?

**Comment by pedro-cf** [comment]
Greetings @potiuk @jscheffl @eladkal @bbovenzi , any chance this issue can be reopened, or should I make a new one?

**Comment by jscheffl** [comment]
As this "Bug" might have a manyfold root cause, some discussions and fixes are on there... I'd propose to open a fresh ticket with the condensed root cause as described (two messages above) with the URL. I assume exactly this case as entry was not covered so far. Then the fix and tests are clear.
