### ISSUE TITLE
500 error occurs while retrieving a task log, Airflow 3.1.0

### ISSUE THREAD

**Issue by opeida** [apache/airflow#56120]
### Apache Airflow version

3.1.0

### What happened?

500 error is returned when trying to access a log of any task. Cloud logging is enabled to GCS.
API server's log contains the following error (the full error listing is provided below): 
`ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner'`

There are also several open issues related to `SUPERVISOR_COMMS`: #51816, #48554.

### Screenshot
<img width="730" height="341" alt="Image" src="https://github.com/user-attachments/assets/a999e31b-d5d5-4a5d-9998-463f43fc3092" />

### What you think should happen instead?

Logs should be retrieved successfully.

### How to reproduce

Access any log of any task.

### Operating System

Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.12.3
apache-airflow-providers-common-compat==1.7.4
apache-airflow-providers-common-io==1.6.3
apache-airflow-providers-common-sql==1.28.1
apache-airflow-providers-fab==2.4.3
apache-airflow-providers-google==18.0.0
apache-airflow-providers-http==5.3.4
apache-airflow-providers-postgres==6.3.0
apache-airflow-providers-redis==4.3.1
apache-airflow-providers-smtp==2.2.1
apache-airflow-providers-standard==1.8.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Deployed on GKE with extended image based on `apache/airflow:slim-3.1.0` and Helm chart 1.18.0.
Migrated from 3.0.6.

### Anything else?

<details><summary>Error listing</summary>
<p>

```
INFO:     10.120.2.16:48230 - "GET /api/v2/dags/integrations.daily_stats/dagRuns/scheduled__2025-09-25T22%3A36%3A12.066275%2B00%3A00/taskInstances/get_ads_stats_data/logs/1?map_index=-1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_utils.py", line 79, in collapse_excgroups
  |     yield
  |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/responses.py", line 271, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 781, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/airflow/.local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/applications.py", line 1082, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 29, in __call__
    |     await responder(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 130, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 46, in __call__
    |     await self.app(scope, receive, self.send_with_compression)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 78, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    |     await response(scope, receive, send)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/responses.py", line 270, in __call__
    |     with collapse_excgroups():
    |          ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/python/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_utils.py", line 85, in collapse_excgroups
    |     raise exc
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/responses.py", line 274, in wrap
    |     await func()
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/responses.py", line 254, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/concurrency.py", line 61, in iterate_in_threadpool
    |     yield await anyio.to_thread.run_sync(_next, as_iterator)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/starlette/concurrency.py", line 50, in _next
    |     return next(iterator)
    |            ^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/log_reader.py", line 134, in read_log_stream
    |     log_stream, out_metadata = self.read_log_chunks(ti, try_number, metadata)
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/log_reader.py", line 104, in read_log_chunks
    |     return self.log_handler.read(ti, try_number, metadata=metadata)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_task_handler.py", line 760, in read
    |     read_result = self._read(task_instance, try_number, metadata)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_task_handler.py", line 614, in _read
    |     sources, logs = self._read_remote_logs(ti, try_number, metadata)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_task_handler.py", line 936, in _read_remote_logs
    |     sources, logs = remote_io.read(path, ti)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/log/gcs_task_handler.py", line 158, in read
    |     blobs = list(self.client.list_blobs(bucket_or_name=bucket, prefix=prefix))
    |                  ^^^^^^^^^^^
    |   File "<attrs generated getattr airflow.providers.google.cloud.log.gcs_task_handler.GCSRemoteLogIO>", line 6, in __getattr__
    |     result = func(self)
    |              ^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/log/gcs_task_handler.py", line 103, in client
    |     if self.hook:
    |        ^^^^^^^^^
    |   File "<attrs generated getattr airflow.providers.google.cloud.log.gcs_task_handler.GCSRemoteLogIO>", line 6, in __getattr__
    |     result = func(self)
    |              ^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/log/gcs_task_handler.py", line 95, in hook
    |     return GCSHook(gcp_conn_id=conn_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 280, in __init__
    |     self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py", line 61, in get_connection
    |     conn = Connection.get(conn_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py", line 226, in get
    |     return _get_connection(conn_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py", line 181, in _get_connection
    |     from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
    | ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fastapi/applications.py", line 1082, in __call__
    await super().__call__(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 29, in __call__
    await responder(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 130, in __call__
    await super().__call__(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/gzip.py", line 46, in __call__
    await self.app(scope, receive, self.send_with_compression)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await response(scope, receive, send)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/responses.py", line 270, in __call__
    with collapse_excgroups():
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/_utils.py", line 85, in collapse_excgroups
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/responses.py", line 274, in wrap
    await func()
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/responses.py", line 254, in stream_response
    async for chunk in self.body_iterator:
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/concurrency.py", line 61, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, as_iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 976, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/starlette/concurrency.py", line 50, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/log_reader.py", line 134, in read_log_stream
    log_stream, out_metadata = self.read_log_chunks(ti, try_number, metadata)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/log_reader.py", line 104, in read_log_chunks
    return self.log_handler.read(ti, try_number, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_task_handler.py", line 760, in read
    read_result = self._read(task_instance, try_number, metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_task_handler.py", line 614, in _read
    sources, logs = self._read_remote_logs(ti, try_number, metadata)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_task_handler.py", line 936, in _read_remote_logs
    sources, logs = remote_io.read(path, ti)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/log/gcs_task_handler.py", line 158, in read
    blobs = list(self.client.list_blobs(bucket_or_name=bucket, prefix=prefix))
                 ^^^^^^^^^^^
  File "<attrs generated getattr airflow.providers.google.cloud.log.gcs_task_handler.GCSRemoteLogIO>", line 6, in __getattr__
    result = func(self)
             ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/log/gcs_task_handler.py", line 103, in client
    if self.hook:
       ^^^^^^^^^
  File "<attrs generated getattr airflow.providers.google.cloud.log.gcs_task_handler.GCSRemoteLogIO>", line 6, in __getattr__
    result = func(self)
             ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/log/gcs_task_handler.py", line 95, in hook
    return GCSHook(gcp_conn_id=conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 280, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py", line 61, in get_connection
    conn = Connection.get(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py", line 226, in get
    return _get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py", line 181, in _get_connection
    from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)
```

</p>
</details> 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sdg9670f** [comment]
got same issue too.
```

[2m2025-09-26T04:23:33.737303Z[0m [[31m[1merror    [0m] [1mcannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)[0m [[0m[1m[34mairflow.task.hooks.airflow.providers.amazon.aws.hooks.logs.AwsLogsHook[0m][0m [36mloc[0m=[35mbase_aws.py:631[0m
--
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 622, in conn_config
connection = self.get_connection(self.aws_conn_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py", line 61, in get_connection
conn = Connection.get(conn_id)
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py", line 226, in get
return _get_connection(conn_id)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py", line 181, in _get_connection
from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)


```

**Comment by gopidesupavan** [comment]
are you both using remote logging? gcs

**Comment by sdg9670f** [comment]
@gopidesupavan yes. using aws cloud watch.

**Comment by shahar1** [comment]
CC: @kaxil

I've closed #56155 that reported an issue in the connection tests, which seems to have the same root cause.
I've managed to reproduce the issue in the connection tests locally.

**Comment by gopidesupavan** [comment]
Thanks both, able to reproduce it, indeed it broke remote logging.  the issue is it is trying to fetch connection but  while fetching the remote log conn id we are not in a  task execution context, so the SUPERVISOR_COMMS is not available.

I have a fix for this and tested working fine it seems, probably we should use it here inprocess api server to fetch the connection.

**Comment by gopidesupavan** [comment]
will try to raise a PR tomorrow

**Comment by kaxil** [comment]
cc @ashb

**Comment by ashb** [comment]
I think this is the compat layer for airflow.hook being triggered, but in the context of api server fetching logs we _dont_ want that here

**Comment by ashb** [comment]
> Thanks both, able to reproduce it, indeed it broke remote logging.  the issue is it is trying to fetch connection but  while fetching the remote log conn id we are not in a  task execution context, so the SUPERVISOR_COMMS is not available.
> 
> I have a fix for this and tested working fine it seems, probably we should use it here inprocess api server to fetch the connection. 

We shouldn't need the in process api server here - we shouldn't even try and hit the compat layer.


ooohhhhh, no here we need a "_reverse_" compat layer. So maybe in process is the right thing here.

@kaxil @amoghrajesh This issue presents some interesting challenges for the API server and the separation in general 🤔

**Comment by gopidesupavan** [comment]
yeah this issue happening when api server access the connection.

**Comment by ms32035** [comment]
I will add, that the same problem affects any plugins that access Airflow connections from within the AP server, after updating imports to point to `airflow.sdk`

**Comment by ashb** [comment]
Possible temporary work around for the log reading side of things: if you are using instance profiles for credentials, then something like this

```
export AIRFLOW_CONN_AWS_DEFAULT=aws://
export AIRFLOW_CONN_GCS_DEFAULT=gcs://
```

might work?

**Comment by jtantry** [comment]
@gopidesupavan, will the resolution be available today for this? Facing the same issue for AWS as well, for 3.1.0.

**Comment by amoghrajesh** [comment]
@jtantry today -- no. Most likely 3.1.1

**Comment by opeida** [comment]
> export AIRFLOW_CONN_GCS_DEFAULT=gcs://

@ashb I set this env variable with Helm but got the same error.

**Comment by jtantry** [comment]
Was facing the error of aws_default not found error, it worked for me when I ran the below command in Airflow : 

```
airflow connections add 'aws_default' \
  --conn-type 'aws' \
  --conn-extra '{"region_name":"eu-west-1"}'
```
And then restarted the scheduler, apiserver and dag-processor services.

**Comment by dishkakrauch** [comment]
Faced same with oss S3 like minio etc

**Comment by ronaldorcampos** [comment]
is there any ETA for this to be fixed and then released? its very problematic not being able to see task logs.

**Comment by ashb** [comment]
@rcampos87 Likely after Airflow Summit as most of the committers and contributors are preparing talks or traveling to it.

However creating the "empty" default connection like jtantry showed https://github.com/apache/airflow/issues/56120#issuecomment-3353840145 should fix the UI again?

**Comment by ronaldorcampos** [comment]
@ashb no, it doesnt solve, my issue is related to this, see https://github.com/apache/airflow/issues/56243

**Comment by Tni04** [comment]
I run Airflow using containers and faced the same issue.
While waiting for an official fix, I applied the changes from the related pull request [#56191](https://github.com/apache/airflow/pull/56191)
 only to the api-server container, and so far everything has been working correctly.

Here is my Dockerfile:

```
FROM apache/airflow:slim-3.1.0-python3.12
EXPOSE 8080
WORKDIR /opt/airflow

ARG INSTALL_MYSQL_CLIENT=false
ARG INSTALL_MSSQL_CLIENT=false

# Copy requirements and webserver_config
COPY ./requirements-apiserver.txt /opt/airflow/requirements.txt
COPY ./webserver_config.py /opt/airflow/webserver_config.py
COPY ./airflow.cfg /opt/airflow/airflow.cfg

# Install uv for faster package installation
RUN pip install uv

# Install Python dependencies using uv
RUN uv pip install --no-cache-dir -r /opt/airflow/requirements.txt

# Fix for the remote logging issue in Airflow
COPY ./airflow-fix/*.py /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/

# Switch to non-root user
USER airflow

CMD ["airflow", "api-server"]
```

**Comment by ms32035** [comment]
While #56243 might be addressing the log retrieval, it does not address the fact that trying something like below in a webserver plugin still returns na error:
```
 File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py", line 61, in get_connection
    conn = Connection.get(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py", line 226, in get
    return _get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py", line 181, in _get_connection
    from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)
```

**Comment by kaxil** [comment]
Another potential solution: https://github.com/apache/airflow/pull/56602

**Comment by shinhoshi57** [comment]
Tried 3.1.1rc1 TAG by manually creating my own image and still present the same issue. Would like to know in which branch this is supposed to be fixed since 3.0+ and remote logging using GCS and KubernetesOperator never worked for me. Logs get created on the GCS bucket but the api-server/UI is unable to read them.

**Comment by ashb** [comment]
@shinhoshi57 what error are you getting please? And assuming 500, what is the error in the API server?

**Comment by shinhoshi57** [comment]
|   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/log/gcs_task_handler.py", line 95, in hook
    |     return GCSHook(gcp_conn_id=conn_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 280, in __init__
    |     self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py", line 61, in get_connection
    |     conn = Connection.get(conn_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py", line 226, in get
    |     return _get_connection(conn_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py", line 181, in _get_connection
    |     from airflow.sdk.execution_time.task_runner import SUPERVISOR_COMMS
    | ImportError: cannot import name 'SUPERVISOR_COMMS' from 'airflow.sdk.execution_time.task_runner' (/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py)

Same as mentioned before.

Just to confirm. I created a custom image by downloading the tag 3.1.1rc1 and uploading it to my own artifact repository:

docker build --platform=linux/amd64 -t eu.gcr.io/XXXXXX/airflow:custom .

 Then from values.yaml chart I used:

# Airflow executor
executor: "KubernetesExecutor"

# Global image settings
images:
  airflow:
    repository: "eu.gcr.io/XXXXXX/airflow"
    tag: "custom"
    pullPolicy: "Always"

**Comment by kaxil** [comment]
The line in Stacktrace doesn't add up for `airflow/sdk/execution_time/context.py`. L181 in Airflow 3.1.1rc1 & Task SDK 1.1.1rc1 should be:

https://github.com/apache/airflow/blob/3.1.1rc1/task-sdk/src/airflow/sdk/execution_time/context.py#L181

https://github.com/apache/airflow/blob/51817f0eeae4f977ea2b6335bcf8804ab920b689/task-sdk/src/airflow/sdk/execution_time/context.py#L180-L183

**Comment by kaxil** [comment]
@shinhoshi57 Did you update both Airflow Core (to 3.1.1rc1) & Task SDK (to 1.1.1rc1) in your custom image?

I checked with `apache/airflow:3.1.1rc1-python3.12` docker image and the line numbers don't line up with your trace

**Comment by shinhoshi57** [comment]
Using this tag apache/airflow:3.1.1rc1-python3.12 (didn't know it was published) it works properly!!!! We have finally logs from GCS working. Thanks kaxil and sorry for the wrong contribution. My docker cache must have played a joke on me.

It works.

For those having issues it is crucial to manually create the connection through the UI.
