### ISSUE TITLE
Backfill Parameters Not Overriding Existing DAG Run Params in Airflow 3

### ISSUE THREAD

**Issue by GeryDeKocliko** [apache/airflow#59043]
### Apache Airflow version

3.1.3

### What happened?

When I run a backfill with parameters on a DAG that already has a DAG run for the same logical date, the parameters from the backfill are not used.

Instead, Airflow reuses the parameters from the existing DAG run (the first run that was created for that logical date). The parameters I specify in the backfill form are ignored.

My use case is that I parallelize work by client:
	•	I have a DAG that runs once per day and can process one specific client based on a parameter (e.g. client_id or data).
	•	I want to be able to backfill only one client for a given day, even if the DAG has already run that day for all clients (or a different client).

Currently, if a DAG run already exists for that date, and I backfill with different parameters, the existing run’s parameters are kept and tasks see the old parameters rather than the new ones.

So effectively:
	•	For new logical dates (no existing DAG run), backfill parameters work as expected.
	•	For existing logical dates, backfill parameters do not override the existing DAG run configuration.

### What you think should happen instead?

When I trigger a backfill for a date range and provide parameters (via “Run Parameters” or JSON configuration), the parameters for each DAG run should:
	•	Be taken from what I provide in the backfill form.
	•	Override any existing parameters or configuration for that logical date.
	•	Be visible inside tasks through:
	•	{{ params.my_param }} in templates
	•	context["params"]["my_param"] in Python code
	•	or a typed ParamsDict argument in a task function.

In other words, if a DAG run already exists for a given execution date and I explicitly launch a backfill with new parameters, I expect those new parameters to be applied to that run (or to a new run), so I can effectively “re-run” that date with different params.

This is important for use cases where:
	•	A single DAG processes multiple clients, selected by a parameter.
	•	We need to re-run only one client for a specific date, even if the date already has a DAG run.

### How to reproduce

Create the following DAG:
```python
from datetime import datetime
from airflow.models.param import Param, ParamsDict
from airflow.decorators import dag, task


@task
def print_data(params: ParamsDict):
    data = params.get("data")
    print(f"DATA --> {data}")


@dag(
    dag_id='test_backfill_with_params',
    start_date=datetime(2023, 1, 1),
    params={
        "data": Param(
            title="My custom data",
            type="string",
            default="Hello World!",
        )
    },
    schedule='@daily',
    catchup=False,
)
def test_backfill_with_params_dag():
    print_data()


test_backfill_with_params_dag()
``` 

Steps:
	1.	Go to the Airflow 3 UI.
	2.	Trigger a manual run for test_backfill_with_params on a given date (e.g. 2025-06-01) with default parameters (or with data = "Hello World!").
	3.	Confirm that the task prints DATA --> Hello World!.
	4.	Now open the Backfill modal for the same DAG.
	5.	Set a date range that includes the same logical date, for example:
	•	Start: 2025-06-01 00:00
	•	End: 2025-06-02 00:00
	6.	In the Run Parameters (or configuration JSON), set:
	•	data = "Overridden Value"
	7.	Trigger the backfill.

Expected:
	•	For the run corresponding to 2025-06-01, the task should receive params["data"] == "Overridden Value".
	•	The log should show something like:
DATA --> Overridden Value

Actual:
	•	For the 2025-06-01 run, the task still sees the original parameter value (e.g. "Hello World!"), or the parameters from the first run that was created for that logical date.
	•	The value provided in the backfill form is ignored for dates that already have a DAG run.

### Operating System

Mac OS 14.6 (23G80)

### Versions of Apache Airflow Providers

No specific providers involved / default set.

### Deployment

Docker-Compose

### Anything else?

This behavior makes it difficult to use a single DAG to process multiple clients in parallel via a parameter, because backfills cannot effectively re-run a single client for a day if a run already exists.

It seems that when a DAG run already exists for a logical date, Airflow reuses that run (including its original params) instead of applying the new configuration provided in the backfill request.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
With "all runs" option the existing runs are cleared without passing params https://github.com/apache/airflow/issues/51439#issuecomment-2949835692 . 

@dstandish Is it intentional to not pass params to existing dagruns during backfill?

https://github.com/apache/airflow/blob/0a1e798fb71520f5848583f63c006c97c6ea7065/airflow-core/src/airflow/models/backfill.py#L355-L364

**Comment by Chris20008** [comment]
I experience this issue on version 3.1.3 as well

**Comment by theobayard** [comment]
Also experiencing this issue

**Comment by icksa** [comment]
I'm also experiencing this, I tried to work around by using the CLI and the "--dag-run-conf" parameter, but I'm seeing the same issue.

**Comment by pgiraudleocare** [comment]
I also face this issue

**Comment by GeryDeKocliko** [comment]
Hello @tirkarthi, @dstandish, @potiuk,

Sorry for the ping — this issue is currently blocking us, and having it resolved would make a huge difference on our side.
Would one of you be able to take a look when you get a moment ?

Best,
Géry

**Comment by potiuk** [comment]
> With "all runs" option the existing runs are cleared without passing params [#51439 (comment)](https://github.com/apache/airflow/issues/51439#issuecomment-2949835692) .
> 
> [@dstandish](https://github.com/dstandish) Is it intentional to not pass params to existing dagruns during backfill?
> 
> [airflow/airflow-core/src/airflow/models/backfill.py](https://github.com/apache/airflow/blob/0a1e798fb71520f5848583f63c006c97c6ea7065/airflow-core/src/airflow/models/backfill.py#L355-L364)
> 
> Lines 355 to 364 in [0a1e798](/apache/airflow/commit/0a1e798fb71520f5848583f63c006c97c6ea7065)
> 
>  if lock: 
>      _handle_clear_run( 
>          session=session, 
>          dag=dag, 
>          dr=dr, 
>          info=info, 
>          backfill_id=backfill_id, 
>          sort_ordinal=backfill_sort_ordinal, 
>          run_on_latest=run_on_latest_version, 
>      )

I think this is a question to @dstandish  mostly - to see if that behaviour is intentional (and why - possibly there is a good reason) - I can imagine changing the dag run parameters for existing DagRuns could be somewhat problematic - but I am not sure if it was a deliberate decision or sometihing that should be fixed (seems like fix might be easy, but maybe also this might require a whole new feature wher user might be able to choose whether to override the params or not for existing DagRuns. The original AIP does not mention it https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-78+Scheduler-managed+backfill but maybe this has been discussed somewhere?

**Comment by ovatarebal** [comment]
experiencing this issue with 3.1.5 also

**Comment by Ramboom** [comment]
"I am also passing the conf parameter during the backfill process; however, it is empty."

**Comment by aru-trackunit** [comment]
Love it @shivaam thank you soo much!

**Comment by amit-beehero** [comment]
Is there anyway to bypass this issue currently if we are unable to update the airflow verison? we are using aws managed version which still doesnt support this one

**Comment by shivaam** [comment]
> Is there anyway to bypass this issue currently if we are unable to update the airflow verison? we are using aws managed version which still doesnt support this one

Unfortunately I don't think there is a supported bypass for this on versions before the fix.

The issue is in the backend reprocess path for existing DagRuns: older versions can accept/pass `dag_run_conf` for the backfill, and new DagRuns can get that conf, but when the backfill reprocesses an existing DagRun it clears/requeues the run without updating `DagRun.conf`. So UI/API/CLI `--dag-run-conf` will still preserve the old config for already-existing logical dates.

**Comment by shivaam** [comment]
> Love it [@shivaam](https://github.com/shivaam) thank you soo much!

You are welcome :)
