### ISSUE TITLE
Airflow scheduler works normally, fails with -D

### ISSUE THREAD

**Issue by yyz940922** [apache/airflow#9071]
Same bug reports as this one: <a href="https://stackoverflow.com/questions/61035608/airflow-scheduler-works-normally-fails-with-d">https://stackoverflow.com/questions/61035608/airflow-scheduler-works-normally-fails-with-d</a>
Environment:
  - Linux: Centos7.6
  - Python 3.7
  - Airflow-version: 1.10.10-Stable
  - Executor: LocalExecutor on MySQL
  - MySQL: 5.7

**Comment by jkoscialkowski** [comment]
Have you tried using different MySQL adapters (e.g. `mysqlclient`) as suggested in the edits to my SO question you linked? I know it is not a full solution, but I was able to make it work this way. You would need to alter the `SQLAlchemy` connection string.

**Comment by turbaszek** [comment]
I thought that this was fixed in 1.10.10 🤔 I'm not familiar with MySQL but maybe @feluelle knows more?

**Comment by feluelle** [comment]
Can't reproduce this issue either. @yyz940922 can you post your sql alchemy conn uri - at least protocol (e.g.`mysql://`) and params (e.g. `charset`), please?

**Comment by yyz940922** [comment]
> Can't reproduce this issue either. @yyz940922 can you post your sql alchemy conn uri - at least protocol (e.g.`mysql://`) and params (e.g. `charset`), please?
sql_alchemy_conn = mysql+pymysql://airflow:password@127.0.0.1:3306/airflow

**Comment by yyz940922** [comment]
I solved this problem in another way, set vm.overcommit_memory=1, then use nohup xxxx &, but -D still not work for scheduler。

**Comment by yyz940922** [comment]
> I solved this problem in another way, set vm.overcommit_memory=1, then use nohup xxxx &, but -D still not work for scheduler。

But this may conflict with the setting of Greenplum, cause vm.overcommit_memory need to be 2 for greenplum。
